In [2]:
# Importing Dependencies
import pandas as pd
from sqlalchemy import create_engine

In [3]:
# Setting csv path and loading the first csv into Pandas DataFrame

tb_rates_csv = "Resources/tb_rates.csv"
tb_rates_df = pd.read_csv(tb_rates_csv)
tb_rates_df.head()

,Country,National data,Report type,2012 Cases,2012 Rate,ASR,Confirmed cases,2011 Cases,2011 Rate,2010 Cases,2010 Rate,2009 Cases,2009 Rate,2008 Cases,2008 Rate
0,Austria,Y,C,648,7.7,7.6,413,690,8.2,691,8.3,696,8.3,817,9.8
1,Belgium,Y,C,987,8.9,9.1,776,1019,9.3,1086,10,994,9.2,990,9.3
2,Bulgaria,Y,C,2280,31.1,30.6,1092,2406,32.6,2649,35,2910,38.3,3150,41.2
3,Cyprus,Y,C,69,8,7.8,50,54,6.4,61,7.4,55,6.9,50,6.3
4,Czech Republic,Y,C,605,5.8,5.6,421,600,5.7,668,6.4,694,6.7,864,8.3

In [6]:
# Dropping unwanted columns

new_df = tb_rates_df.drop(["National data", "Report type", "ASR", "Confirmed cases"], axis=1)
new_df.head()

,Country,2012 Cases,2012 Rate,2011 Cases,2011 Rate,2010 Cases,2010 Rate,2009 Cases,2009 Rate,2008 Cases,2008 Rate
0,Austria,648,7.7,690,8.2,691,8.3,696,8.3,817,9.8
1,Belgium,987,8.9,1019,9.3,1086,10,994,9.2,990,9.3
2,Bulgaria,2280,31.1,2406,32.6,2649,35,2910,38.3,3150,41.2
3,Cyprus,69,8,54,6.4,61,7.4,55,6.9,50,6.3
4,Czech Republic,605,5.8,600,5.7,668,6.4,694,6.7,864,8.3

In [8]:
# Dropping Unwanted role by index

new_tb_rates_df = tb_rates_df.drop([27, 29], axis=0)
new_tb_rates_df.head()

,Country,National data,Report type,2012 Cases,2012 Rate,ASR,Confirmed cases,2011 Cases,2011 Rate,2010 Cases,2010 Rate,2009 Cases,2009 Rate,2008 Cases,2008 Rate
0,Austria,Y,C,648,7.7,7.6,413,690,8.2,691,8.3,696,8.3,817,9.8
1,Belgium,Y,C,987,8.9,9.1,776,1019,9.3,1086,10,994,9.2,990,9.3
2,Bulgaria,Y,C,2280,31.1,30.6,1092,2406,32.6,2649,35,2910,38.3,3150,41.2
3,Cyprus,Y,C,69,8,7.8,50,54,6.4,61,7.4,55,6.9,50,6.3
4,Czech Republic,Y,C,605,5.8,5.6,421,600,5.7,668,6.4,694,6.7,864,8.3

In [77]:
eu_countries = new_tb_rates_df["Country"]
eu_list = eu_countries.to_list()
eu_list

['Austria',
 'Belgium',
 'Bulgaria',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hungary',
 'Ireland',
 'Italy',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Malta',
 'Netherlands',
 'Poland',
 'Portugal',
 'Romania',
 'Slovakia',
 'Slovenia',
 'Spain',
 'Sweden',
 'United Kingdom',
 'Iceland',
 'Norway']

In [39]:
immunisation_csv = "./datasets/BSG_NEW.csv"
immunisation_df = pd.read_csv(immunisation_csv)
immunisation_df

                                Country  2012  2011  2010  2009  2008
0                           Afghanistan  78.0  71.0  68.0  64.0  66.0
1                               Albania  96.0  97.0  99.0  97.0  99.0
2                               Algeria  99.0  99.0  99.0  99.0  99.0
3                                Angola  73.0  74.0  79.0  70.0  73.0
4                             Argentina  99.0  99.0  99.0  99.0  99.0
..                                  ...   ...   ...   ...   ...   ...
159  Venezuela (Bolivarian Republic of)  96.0  95.0  92.0  91.0  90.0
160                            Viet Nam  98.0  98.0  94.0  97.0  92.0
161                               Yemen  64.0  59.0  65.0  58.0  60.0
162                              Zambia  92.0  92.0  92.0  92.0  91.0
163                            Zimbabwe  98.0  98.0  99.0  90.0  91.0

[164 rows x 6 columns]

In [97]:
eu_df = immunisation_df.loc[immunisation_df["Country"] == new_tb_rates_df["Country"]]
eu_df
#==new_tb_rates_df.loc["Country"]]

ValueError: Can only compare identically-labeled Series objects

In [81]:
boolean_df = immunisation_df.isin([eu_list])
boolean_df.head(53)

    Country   2012   2011   2010   2009   2008
0     False  False  False  False  False  False
1     False  False  False  False  False  False
2     False  False  False  False  False  False
3     False  False  False  False  False  False
4     False  False  False  False  False  False
5     False  False  False  False  False  False
6     False  False  False  False  False  False
7     False  False  False  False  False  False
8     False  False  False  False  False  False
9     False  False  False  False  False  False
10    False  False  False  False  False  False
11    False  False  False  False  False  False
12    False  False  False  False  False  False
13    False  False  False  False  False  False
14    False  False  False  False  False  False
15    False  False  False  False  False  False
16    False  False  False  False  False  False
17    False  False  False  False  False  False
18    False  False  False  False  False  False
19    False  False  False  False  False  False
20    False  False  False  False  False  False
21    False  False  False  False  False  False
22    False  False  False  False  False  False
23    False  False  False  False  False  False
24    False  False  False  False  False  False
25    False  False  False  False  False  False
26    False  False  False  False  False  False
27    False  False  False  False  False  False
28    False  False  False  False  False  False
29    False  False  False  False  False  False
30    False  False  False  False  False  False
31    False  False  False  False  False  False
32    False  False  False  False  False  False
33    False  False  False  False  False  False
34    False  False  False  False  False  False
35    False  False  False  False  False  False
36    False  False  False  False  False  False
37    False  False  False  False  False  False
38    False  False  False  False  False  False
39    False  False  False  False  False  False
40    False  False  False  False  False  False
41    False  False  False  False  False  False
42    False  False  False  False  False  False
43    False  False  False  False  False  False
44    False  False  False  False  False  False
45    False  False  False  False  False  False
46    False  False  False  False  False  False
47    False  False  False  False  False  False
48    False  False  False  False  False  False
49    False  False  False  False  False  False
50    False  False  False  False  False  False
51    False  False  False  False  False  False
52    False  False  False  False  False  False

In [104]:
protocol = 'postgresql'
username = '<postgresql>'
password = '<password>'
host = 'localhost'
port = 5432
database_name = 'tuberculosis_db'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

In [101]:
pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.3-cp37-cp37m-win_amd64.whl (1.1 MB)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.3
Note: you may need to restart the kernel to use updated packages.

In [105]:
engine.table_names()

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "<postgresql>"

(Background on this error at: http://sqlalche.me/e/e3q8)