In [118]:
import pandas as pd
from sqlalchemy import create_engine

In [123]:
tb_rates_csv = "Resources/tb_rates.csv"
tb_rates_df = pd.read_csv(tb_rates_csv)
tb_rates_df.head()

,Country,National data,Report type,2012 Cases,2012 Rate,ASR,Confirmed cases,2011 Cases,2011 Rate,2010 Cases,2010 Rate,2009 Cases,2009 Rate,2008 Cases,2008 Rate
0,Austria,Y,C,648,7.7,7.6,413,690,8.2,691,8.3,696,8.3,817,9.8
1,Belgium,Y,C,987,8.9,9.1,776,1019,9.3,1086,10,994,9.2,990,9.3
2,Bulgaria,Y,C,2280,31.1,30.6,1092,2406,32.6,2649,35,2910,38.3,3150,41.2
3,Cyprus,Y,C,69,8,7.8,50,54,6.4,61,7.4,55,6.9,50,6.3
4,Czech Republic,Y,C,605,5.8,5.6,421,600,5.7,668,6.4,694,6.7,864,8.3

In [129]:
tb_rates_df.drop(["National data", "Report type", "ASR", "Confirmed cases"], axis=1, inplace=True)

In [130]:
new_tb_rates_df = tb_rates_df.drop([27, 29], axis=0)
new_tb_rates_df.head()

,Country,2012 Cases,2012 Rate,2011 Cases,2011 Rate,2010 Cases,2010 Rate,2009 Cases,2009 Rate,2008 Cases,2008 Rate
0,Austria,648,7.7,690,8.2,691,8.3,696,8.3,817,9.8
1,Belgium,987,8.9,1019,9.3,1086,10,994,9.2,990,9.3
2,Bulgaria,2280,31.1,2406,32.6,2649,35,2910,38.3,3150,41.2
3,Cyprus,69,8,54,6.4,61,7.4,55,6.9,50,6.3
4,Czech Republic,605,5.8,600,5.7,668,6.4,694,6.7,864,8.3

In [77]:
eu_countries = new_tb_rates_df["Country"]
eu_list = eu_countries.to_list()
eu_list

['Austria',
 'Belgium',
 'Bulgaria',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hungary',
 'Ireland',
 'Italy',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Malta',
 'Netherlands',
 'Poland',
 'Portugal',
 'Romania',
 'Slovakia',
 'Slovenia',
 'Spain',
 'Sweden',
 'United Kingdom',
 'Iceland',
 'Norway']

In [127]:
immunisation_csv = "Resources/BCG.csv"
immunisation_df = pd.read_csv(immunisation_csv)
immunisation_df.head()

       Country  2012  2011  2010  2009  2008
0  Afghanistan  78.0  71.0  68.0  64.0  66.0
1      Albania  96.0  97.0  99.0  97.0  99.0
2      Algeria  99.0  99.0  99.0  99.0  99.0
3       Angola  73.0  74.0  79.0  70.0  73.0
4    Argentina  99.0  99.0  99.0  99.0  99.0

In [131]:
clean_data = immunisation_df[immunisation_df['Country'].isin(new_tb_rates_df['Country'])==True]
clean_data

       Country  2012  2011  2010  2009  2008
17    Bulgaria  97.0  98.0  98.0  98.0  98.0
46     Estonia  97.0  99.0  97.0  97.0  98.0
50     Finland   NaN   NaN   NaN   NaN   NaN
51      France   NaN   NaN   NaN   NaN   NaN
62     Hungary  99.0  99.0  99.0  99.0  99.0
67     Ireland  42.0  41.0  30.0  30.0  34.0
77      Latvia  94.0  93.0  92.0  96.0  95.0
81   Lithuania  98.0  98.0  99.0  99.0  99.0
113     Poland  94.0  94.0  93.0  94.0  93.0
114   Portugal  99.0  97.0  96.0  98.0  98.0
119    Romania  99.0  99.0  99.0  99.0  99.0
133   Slovakia  90.0  97.0  98.0  97.0  98.0
134   Slovenia   NaN   NaN   NaN   NaN   NaN
141     Sweden  24.0  23.0  23.0  21.0  23.0

In [104]:
protocol = 'postgresql'
username = '<postgresql>'
password = '<password>'
host = 'localhost'
port = 5432
database_name = 'tuberculosis_db'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

In [105]:
engine.table_names()

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "<postgresql>"

(Background on this error at: http://sqlalche.me/e/e3q8)